# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M.C. Dickson
email: mark@thegreengorcrow.com
description: > # this means to ignore newlines until "baseurl:"
  The writings of the author M.C. Dickson
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mcdickson.com" # the base hostname & protocol for your site
twitter_username: thegreengorcrow
github_username:  markcdickson-author

# Build settings
markdown: kramdown
